version: "3"

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    container_name: nginx-pagespeed
    env_file: .env
    volumes:
      - ./ssl:/etc/ssl
